version: "3.7"

x-yarp-base: &yarp-base
  image: icubteamcode/supervise-calib:v2022.02.0_sources
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/root/.Xauthority
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "${XAUTHORITY}:/root/.Xauthority"
    - "${HOME}/${YARP_CONF_PATH}:/root/.config/yarp"
    - "/dev:/dev"
  network_mode: "host"
  privileged: true



services:
  
 #------------------------------------------------------------------------------------------------
  #Calling calibCamTilt module 
  
  yDemoCalibCamTilt:
    <<: *yarp-base
    command: sh -c "if [ ! -z ${LEFT_CUSTOM_PORT} ]; then yarp wait ${LEFT_CUSTOM_PORT}; else yarp wait /icub/cam/left; fi; calibCamTilt" 
 
#------------------------------------------------------------------------------------------------
  #Opening the viewer to see the left output image
  yview_right_img_o:
    <<: *yarp-base
    command: sh -c "if [ -f "/root/.config/yarp/yarp_namespace.conf" ]; then yarp wait $$(echo $$(cat /root/.config/yarp/yarp_namespace.conf)); else yarp wait /root; fi; yarpview --name /leftImageOutput"

  #Opening we open the viewer to see the right output image
  yview_left_img_o:
    <<: *yarp-base
    command: sh -c "if [ -f "/root/.config/yarp/yarp_namespace.conf" ]; then yarp wait $$(echo $$(cat /root/.config/yarp/yarp_namespace.conf)); else yarp wait /root; fi; yarpview --name /rightImageOutput"











