version: "3.7"
x-yarp-base: &yarp-base

  image: last_test_laptop:latest
  environment:
  - DISPLAY=${{DISPLAY}}
  - QT_X11_NO_MITSHM=1
  - XAUTHORITY=/root/.Xauthority
  - YARP_FORWARD_LOG_ENABLE=1
  - YARP_ROBOT_NAME
  volumes:
  - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
  - "${{XAUTHORITY}}:/root/.Xauthority:rw"
  - "${{YARP_CONF_PATH}}:/root/.config/yarp"

  ports:
  - "10000:10000"
  network_mode: "host"
  privileged: true
services:
  yarpdev_0:
    <<: *yarp-base
    command: sh -c yarp detect --write; yarpdev --device test_grabber --width 640
      --height 480
