version: "3.7"
x-yarp-base: &yarp-base

  image: using_promises:latest
  environment:
  - DISPLAY=${{DISPLAY}}
  - QT_X11_NO_MITSHM=1
  - XAUTHORITY=/root/.Xauthority
  - YARP_FORWARD_LOG_ENABLE=1
  - YARP_ROBOT_NAME
  volumes:
  - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
  - "${{XAUTHORITY}}:/root/.Xauthority:rw"
  - "${{YARP_CONF_PATH}}:/root/.config/yarp"
  networks:
  - hostnet

services:
  yserver:
    <<: *yarp-base
    deploy:
      placement:
        constraints: [node.role == manager]
      command: sh -c "yarp where | grep 'is available at ip' > /dev/null ; if [ !
        $$? -eq 0 ]; then yarpserver --write; fi"
  yconnect_0:
    <<: *yarp-base
    deploy:
      restart_policy:
        condition: on-failure
    command: sh -c yarp detect --write; yarp wait /grabber; yarp wait /view; yarp
      connect /grabber /view fast_tcp
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
    - "8080:8080"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  hostnet:
    external: true
    name: host
