version: "3.7"

x-yarp-gazebo: &yarp-gazebo
  image: icubteamcode/grasp-the-ball-gazebo:v2022.02.0_sources
  environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/root/.Xauthority
    - YARP_FORWARD_LOG_ENABLE=1
    - YARP_ROBOT_NAME
    - APPSAWAY_ROBOT_MODEL
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "${XAUTHORITY}:/root/.Xauthority"
    - "${HOME}/${YARP_CONF_PATH}:/root/.config/yarp"
    - "${HOME}/teamcode/appsAway/demos/graspTheBallGazebo/gazebo/models/red-ball:/projects/iCubContrib/share/gazebo/models/red-ball"
    - "${HOME}/teamcode/appsAway/demos/graspTheBallGazebo/gazebo/worlds/grasp-ball-gazebo.sdf:/projects/iCubContrib/share/gazebo/worlds/grasp-ball-gazebo.sdf"
    - "${HOME}/teamcode/appsAway/demos/graspTheBallGazebo/gazebo/libdemoRedBall-world.so:/projects/iCubContrib/lib/libdemoRedBall-world.so"
  ports:
    - "10000:10000"
  network_mode: "host"
  privileged: true
  #ipc: host

services:

  ygazebo:
    <<: *yarp-gazebo
    command: sh -c "if [ -f "/root/.config/yarp/yarp_namespace.conf" ]; then yarp wait $$(echo $$(cat /root/.config/yarp/yarp_namespace.conf)); else yarp wait /root; fi; gazebo grasp-ball-gazebo.sdf --verbose"

#following services are configured in ./icub-main/app/default/scripts/cameras_calib.xml.template
  yview_l:
    <<: *yarp-gazebo
    command: sh -c "yarp wait /icubSim/cam/left/rgbImage:o; yarpview --name /icubSim/view/left --x 0 --y 0 --p 50 --compact"

  yview_r:
    <<: *yarp-gazebo
    command: sh -c "yarp wait /icubSim/cam/left/rgbImage:o; yarpview --name /icubSim/view/right --x 400 --y 0 --p 50 --compact"


#-----------------------------------------------------------------------------------------------------------------------------------------------------
#Following services are configured in icub-basic-demos/demoRedBall/app/scripts/demoRedBall.xml.template
  yview:
    <<: *yarp-gazebo
    command: sh -c "yarp wait /pf3dTracker/video:o; yarpview --name /PF3DTracker_viewer --x 750 --y 0 --p 50 --compact"

